name: knewkarma
icon: snap/gui/icon512x512.png
title: Knew Karma
summary: A Reddit data analysis toolkit
description: |
  **Knew Karma** (/nuː ‘kɑːrmə/) is a Reddit data analysis toolkit designed to provide an extensive range of
  functionalities for exploring and analysing Reddit data. It includes a **Command-Line Interface (CLI)**, and an
  **Application Programming Interface (API)** to enable an easy integration in other Python Projects. Refer to the documentation (https://knewkarma.readthedocs.io) for the **usage** and **integration** guide.
license: GPL-3.0+
version: "0.1"

base: core22
grade: stable
confinement: strict
adopt-info: knewkarma

source-code: https://github.com/rly0nheart/knewkarma
issues:
  - https://github.com/rly0nheart/knewkarma/issues
donation:
  - https://opencolletive.com/knewkarma
contact:
  - mailto:rly0nheart@duck.com

parts:
  knewkarma:
    plugin: python
    source: .
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags --always)"
    override-build: |
      snapcraftctl build
      # Ensure all commit history is available
      git fetch --unshallow || true

type: app
apps:
  knewkarma:
    command: bin/knewkarma
    desktop: snap/gui/knewkarma.desktop
    plugs: [ network, network-bind, home ]
